// src/controls/agenticCommandParser.js
import { CommandTypes, WORKSPACE_BOUNDS } from '../core/commandTypes.js';
import { validateCommand } from '../core/safetyValidator.js';
import { getRobotState, getRobotAdapter } from '../core/robotStore.js';

/**
 * Extracts a JSON block from potentially text-wrapped model outputs (like markdown code blocks).
 * 
 * @param {string} text - Raw string output from the LLM
 * @returns {Object} Parsed JSON object
 */
export function extractJSON(text) {
  if (!text) throw new Error("Empty model response.");
  
  // Try to find markdown json code block
  const codeBlockRegex = /```json\s*([\s\S]*?)\s*```/;
  const match = text.match(codeBlockRegex);
  const cleanText = match ? match[1] : text;

  // Find the first '{' and the last '}'
  const startIdx = cleanText.indexOf('{');
  const endIdx = cleanText.lastIndexOf('}');
  
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error("Could not find a valid JSON object in response.");
  }
  
  const jsonString = cleanText.substring(startIdx, endIdx + 1);
  return JSON.parse(jsonString);
}

/**
 * Normalizes commands generated by the LLM and forces the 'agentic-voice' source tag.
 * 
 * @param {Object} rawCmd - The raw command object generated by the LLM
 * @returns {Object} Normalized command conforming to internal commandTypes
 */
export function normalizeAgenticCommand(rawCmd) {
  if (!rawCmd || typeof rawCmd !== 'object') {
    throw new Error("Invalid command format in sequence.");
  }

  // Force lowercase source tag
  const cmd = {
    ...rawCmd,
    source: 'agentic-voice'
  };

  // Convert old type labels to internal ones if needed
  if (cmd.type === 'MOVE_TO') cmd.type = 'moveTo';
  if (cmd.type === 'JOG') cmd.type = 'jog';
  if (cmd.type === 'TAP_KEY' || cmd.type === 'TAP' || cmd.type === 'press') cmd.type = 'pressKey';
  if (cmd.type === 'EXECUTE_PIN' || cmd.type === 'RUN_PIN') cmd.type = 'runPin';
  if (cmd.type === 'HOME') cmd.type = 'home';
  if (cmd.type === 'STOP') cmd.type = 'stop';
  if (cmd.type === 'ROTATE_JOINT') cmd.type = 'rotateJoint';

  return cmd;
}

/**
 * Simulates an LLM agent response locally for common testing and presentation commands.
 * Runs offline to provide a seamless fallback experience if no Gemini API Key is configured.
 * 
 * @param {string} transcript - Normalized text transcript
 * @param {Object} currentEE - Current end effector position {x, y, z}
 * @returns {Array<Object>|null} List of commands or null if not simulated
 */
export function simulateLocalAgenticResponse(transcript, currentEE) {
  const norm = (transcript || '').toLowerCase().trim();

  // Define a guaranteed reachable safe start zone for complex path shapes
  // This avoids physical extension limits when drawing starting from fully stretched home position.
  const safeStart = { x: 0.50, y: 0.00, z: 0.25 };

  // Case A: Draw a triangle
  if (norm.includes('draw a triangle') || norm.includes('make a triangle')) {
    return [
      { type: 'moveTo', target: { x: 0.45, y: -0.10, z: 0.25 } },
      { type: 'moveTo', target: { x: 0.55, y: 0.00, z: 0.35 } },
      { type: 'moveTo', target: { x: 0.45, y: 0.10, z: 0.25 } },
      { type: 'moveTo', target: { x: 0.45, y: -0.10, z: 0.25 } }
    ];
  }

  // Case B: Draw a square
  if (norm.includes('draw a square') || norm.includes('draw a box') || norm.includes('square path')) {
    return [
      { type: 'moveTo', target: { x: 0.45, y: -0.10, z: 0.25 } },
      { type: 'moveTo', target: { x: 0.55, y: -0.10, z: 0.25 } },
      { type: 'moveTo', target: { x: 0.55, y: 0.10, z: 0.25 } },
      { type: 'moveTo', target: { x: 0.45, y: 0.10, z: 0.25 } },
      { type: 'moveTo', target: { x: 0.45, y: -0.10, z: 0.25 } }
    ];
  }

  // Case C: Draw a circle
  if (norm.includes('draw a circle') || norm.includes('make a circle') || norm.includes('circle path')) {
    const r = 0.08; // 8cm radius
    const points = [];
    for (let i = 0; i <= 8; i++) {
      const angle = (i * 2 * Math.PI) / 8;
      points.push({
        type: 'moveTo',
        target: {
          x: safeStart.x + r * Math.cos(angle),
          y: safeStart.y + r * Math.sin(angle),
          z: safeStart.z
        }
      });
    }
    return points;
  }

  // Case D: Draw a pentagon
  if (norm.includes('pentagon')) {
    const r = 0.08;
    const points = [];
    for (let i = 0; i <= 5; i++) {
      const angle = (i * 2 * Math.PI) / 5 - Math.PI / 2; // Offset to start at top
      points.push({
        type: 'moveTo',
        target: {
          x: safeStart.x + r * Math.cos(angle),
          y: safeStart.y + r * Math.sin(angle),
          z: safeStart.z
        }
      });
    }
    return points;
  }

  // Case E: Draw a cross
  if (norm.includes('cross')) {
    return [
      { type: 'moveTo', target: { x: safeStart.x - 0.08, y: safeStart.y, z: safeStart.z } },
      { type: 'moveTo', target: { x: safeStart.x + 0.08, y: safeStart.y, z: safeStart.z } },
      { type: 'moveTo', target: { x: safeStart.x, y: safeStart.y, z: safeStart.z } },
      { type: 'moveTo', target: { x: safeStart.x, y: safeStart.y - 0.08, z: safeStart.z } },
      { type: 'moveTo', target: { x: safeStart.x, y: safeStart.y + 0.08, z: safeStart.z } }
    ];
  }

  // Case F: Rotate arm/base
  if (norm.includes('rotate base') || norm.includes('rotate arm') || norm.includes('rotate your arm') || norm.includes('rotate')) {
    let degrees = 30;
    const degMatch = norm.match(/(\d+)\s*degree/);
    if (degMatch) {
      degrees = parseInt(degMatch[1], 10);
    }
    if (norm.includes('left') || norm.includes('counter') || norm.includes('minus') || norm.includes('negative')) {
      degrees = -degrees;
    }
    const adapter = getRobotAdapter();
    const baseJointName = adapter ? adapter.getBaseJointName() : 'joint_1';
    return [
      { type: 'rotateJoint', jointName: baseJointName, deltaDeg: degrees }
    ];
  }

  // Case G: Hover over key sequence
  // e.g. "press keys 1 3 5" or "press key 2 then 4"
  const digitRegex = /\b(press|tap|keys)\s+([1-6\s,thenand]+)\b/;
  const match = norm.match(digitRegex);
  if (match) {
    const digits = match[2].replace(/[^1-6]/g, '');
    if (digits.length > 0) {
      return digits.split('').map(d => ({ type: 'pressKey', key: d }));
    }
  }

  // Case H: Return to safe default zone
  if (norm.includes('safe zone') || norm.includes('safe position') || norm.includes('clearance')) {
    return [
      { type: 'moveTo', target: { x: 0.55, y: 0.0, z: 0.30 } }
    ];
  }

  return null;
}

/**
 * Formulates the system instructions prompt containing constraints and contextual telemetry.
 */
function buildSystemPrompt(currentEE, currentJoints, keyConfig, transcript) {
  return `
You are the AI agentic brain of a 6-DOF robotic arm simulator.
Your job is to parse the operator's natural language voice request into a structured JSON plan of movement commands.

Allowed command types:
1. moveTo: Moves the end-effector to an absolute 3D target. target coordinate object must be {x, y, z}.
2. jog: Jogs a single axis. payload: { axis: 'x'|'y'|'z', delta: number } (delta must be between -0.10 and 0.10 meters).
3. pressKey: Taps a key. payload: { key: '1'|'2'|'3'|'4'|'5'|'6' }.
4. runPin: Taps a 6-digit sequence of keys. payload: { pin: string of 6 digits '1'-'6' }.
5. home: Moves the arm to the home position.
6. stop: Stops any active movements.
7. rotateJoint: Rotates a specific joint. payload: { jointName: string, deltaDeg: number }.

SYSTEM CONTEXT:
- Current End-Effector (Stylus Tip) Position: ${JSON.stringify(currentEE)}
- Current Joint Angles (radians): ${JSON.stringify(currentJoints)}
- Key coordinates configurations (for tap coordinates reference): ${JSON.stringify(keyConfig)}

WORKSPACE BOUNDARIES (Meters):
- X limit: [${WORKSPACE_BOUNDS.x.min}, ${WORKSPACE_BOUNDS.x.max}]
- Y limit: [${WORKSPACE_BOUNDS.y.min}, ${WORKSPACE_BOUNDS.y.max}]
- Z limit: [${WORKSPACE_BOUNDS.z.min}, ${WORKSPACE_BOUNDS.z.max}] (Note: Z=0 is the floor).

OPERATOR REQUEST TRANSCRIPT:
"${transcript}"

CRITICAL INSTRUCTIONS:
- You must output valid JSON containing a single root key "commands", which contains an array of commands.
- Do NOT output any markdown code blocks, backticks, or explanatory text before or after the JSON. Return only the raw JSON.
- Every coordinate target you generate MUST lie within the workspace limits. If a target is outside, discard it or clamp it.
- REACHABLE SAFE ZONE FOR DRAWING SHAPES: If drawing shapes (like triangles, squares, circles, etc.), generate targets centered around a safe reachable zone: X: [0.45, 0.58], Y: [-0.15, 0.15], Z: [0.20, 0.35]. Do not try to draw shapes at the outer reach of the arm (e.g. at the home position limits where X is near 0.7+), otherwise the inverse kinematics solver will fail to converge!
- If the operator's request is physically impossible or violates safety limits, return an empty commands array and add an "error" message field.
`;
}

/**
 * Parses a natural language transcript using the Gemini API or a local fallback.
 * Validates the output schema and runs safety validator gating on all generated actions.
 * 
 * @param {string} transcript - Natural language voice transcript
 * @param {Object} [context={}] - Pipeline runtime context
 * @returns {Promise<Object>} Parser report { ok: boolean, commands: Array, source: 'agentic-voice', mode: string }
 */
export async function parseAgenticCommand(transcript, context = {}) {
  const state = getRobotState();
  const currentEE = state.eePosition || { x: 0.55, y: 0.0, z: 0.10 };
  const currentJoints = state.jointAngles || {};
  const keyConfig = context.keyConfig || {};

  let mode = 'local-simulation';
  let commands = [];

  // 1. Try local rules simulator first (for offline capability or default presets)
  const simulated = simulateLocalAgenticResponse(transcript, currentEE);
  
  if (simulated) {
    commands = simulated;
    mode = 'local-simulation';
  } else {
    // 2. Query Backend Gemini Proxy API
    mode = 'gemini-api';
    try {
      const promptText = buildSystemPrompt(currentEE, currentJoints, keyConfig, transcript);
      
      const url = `/api/agentic-voice`;
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: promptText })
      });

      if (!response.ok) {
        const errJson = await response.json().catch(() => ({}));
        let errMsg = typeof errJson.error === 'object' && errJson.error !== null
          ? (errJson.error.message || JSON.stringify(errJson.error))
          : (errJson.error || `Proxy server returned status ${response.status}`);

        if (response.status === 429 || errMsg.toLowerCase().includes('quota') || errMsg.toLowerCase().includes('exhausted') || errMsg.toLowerCase().includes('limit')) {
          errMsg = `Gemini Quota Exceeded (429: Too Many Requests). Please wait a moment or check your billing plan. Details: ${errMsg}`;
        }
        throw new Error(errMsg);
      }

      const resData = await response.json();
      const outputText = resData?.candidates?.[0]?.content?.parts?.[0]?.text;
      
      if (!outputText) {
        throw new Error("No text content returned from Gemini Model.");
      }

      const parsedJson = extractJSON(outputText);
      commands = parsedJson.commands || [];

      if (parsedJson.error) {
        return {
          ok: false,
          message: `Gemini Agent Rejected Request: ${parsedJson.error}`,
          transcript,
          mode
        };
      }
    } catch (err) {
      console.warn("Backend Gemini API call failed. Error:", err.message);
      return {
        ok: false,
        message: `Gemini Agent Error: ${err.message}`,
        transcript,
        mode
      };
    }
  }

  if (!Array.isArray(commands) || commands.length === 0) {
    return {
      ok: false,
      message: "Agent generated no executable actions.",
      transcript,
      mode
    };
  }

  // 3. Schema Validation & Gated Safety Validator Checks
  const validatedCommands = [];
  const safetyContext = {
    robotAdapter: context.robotAdapter,
    keyConfig: context.keyConfig
  };

  for (let i = 0; i < commands.length; i++) {
    try {
      const rawCmd = commands[i];
      const normalized = normalizeAgenticCommand(rawCmd);
      
      // Perform strict safety gate validation
      const safetyResult = validateCommand(normalized, safetyContext);
      if (!safetyResult.ok) {
        return {
          ok: false,
          message: `Agentic sequence step [${i + 1}/${commands.length}] (${normalized.type}) failed safety check: ${safetyResult.message}`,
          transcript,
          mode
        };
      }

      validatedCommands.push(normalized);
    } catch (err) {
      return {
        ok: false,
        message: `Command schema error at step [${i + 1}]: ${err.message}`,
        transcript,
        mode
      };
    }
  }

  return {
    ok: true,
    commands: validatedCommands,
    transcript,
    mode,
    message: `Generated safe sequence of ${validatedCommands.length} step(s) via ${mode === 'gemini-api' ? 'Gemini' : 'Local Simulator'}.`
  };
}
